= Firearms 101 Instructor Script

// This instructor script should serve as a guideline on how to teach your course.

// It is written to be memorized and repeated, so it contains phrases and colloquialisms that may come off as abnormal if they aren't part of your normal lexicon. Feel free to edit and make it your own!

// The important bits are in bold. Do not delete the important bits. They can be re-phrased, but they are the key points needed to make this course effective

== Slide 1 and 2: Introduction and Outline
// Slide 1
Welcome to our Intro to firearms course. Hopefully by the end of this, you'll have the information you need to handle a firearm safely at the range so your focus can be on effective shooting and having fun with the rest of the chapter.

// Slide 2

We're going to start off talking about firearms safety. Before we get into the exciting stuff, we have to cover the boring stuff so no one shoots themselves in the foot. Firearms are dangerous, and we want to make sure everyone handles them with the respect they deserve before we get into the nitty-gritty.

Then we'll go into firearms operation. We'll talk about how firearms actually work, on a mechanical level, and other important concepts that aren't exactly shooting, but are important to shooting.

Finally, we'll go over how to actually make the gun go bang and put the bullet on target. That includes things like holding the firearm properly, how to take aim, and what to do when your boom-stick doesn't go boom.

== Slide 3: Firearms Accidents and Injuries Discussion

I think we all know that firearms are dangerous. These are weapons. They are meant to kill. But, being responsible with your firearm can drastically reduce the chance of accidental deaths or injuries.

Let's *talk about* some things y'all think we should do that could minimize *accidental deaths and injuries from firearms.*

// Try to lead the conversation here towards the six rules. When you move on, connect back to some of the ideas that came out of the brainstorming session. This should cement that the 6 rules are intuitive and easy to understand.

== Slide 4: 6 Rules of Firearms Safety

Has anyone heard of the four rules of firearms safety?

Traditionally, there are four rules of firearms safety. They're pretty easy, and they make a lot of sense.

// Try to connect back to the discussion if possible

* *Treat all firearms as if they were loaded*
* *Never point a firearm at anything you're not willing to destroy*
* *Keep your finger off of the trigger and outside of the trigger guard*
* *Be sure of your target, what's in your line of fire, and what's beyond it*

Pretty easy right? And, they all make a lot of sense. At the end of the day, it's all about making sure the functional parts of the firearm (the barrel, the trigger, the bullet) are in complete control of the person holding the gun.

Let's talk about our other two rules:

* *Always Wear Appropriate Eye and Ear Protection*

This doesn't mean you carry ear protection with you everywhere you go, and when a person is trying to attack you you say "WAIT I HAVE TO PUT MY EAR PLUGS IN". That wont work, they aren't waiting. What it DOES mean, is that any time you're practicing with your firearm, your eyes and ears should be protected because they're extremely important and once they're damaged they don't heal well-if at all.

Finally:

* *Be Aware of Your Mental State*

You absolutely should not have a firearm in your possession if you are in an altered mental state. If you've drank, even one drink? No gun. Smoked weed? No gun. Having a mental health crisis? No gun.

// Toss a personal story in here if you can. Mental health crises are real, and if you can make it real for your students it'll help cement this rule in their mind

I was in a spot not too long ago where my mental health took a nosedive. I'm lucky enough to have a comrade who came to my house, talked to me for a bit to see what was up, and agreed to take my firearm. When I called a couple of weeks later and told him it was all good and I was feeling better and wanted my gun back, he came over, we chatted for a second about what happened and how I was feeling, and he gave it back.

Hold your comrades accountable, and be there for them. That means calling your comrades out if they're intoxicated and trying to handle a firearm, but it also means build relationships with your comrades so when something goes wrong, they've got a place to take their firearm if things get dark.

Let's review the rules. We're going to list them, out loud, together. These rules need to be automatic, because they're so foundational to being safe around firearms.

== Slide 5: Safe Transportation and Handoff

​​​​​​​Moving on from the rules, let's talk about cases, transport, and safe handoff of firearms. *Generally, it's a bad idea to just throw your firearm in any old bag and let it roll around in there. the trigger is unprotected, and if it's loaded something could easily catch the trigger and fire off a round. The purpose of a good firearm case is not only to protect your firearm while you're transporting it, it's also to keep your firearm from accidentally going off.*

It's best if your firearm is in a case that's made for it. Luckily, most handguns come with a plastic case. Rifles don't come with a case (? Maybe?) so it's a good idea for you to get one, or to transport it unloaded.

Soft cases vs hard cases are a bit of a personal choice. Hard cases can help protect against things like accidentally bumping your soft case and throwing your optic off, and they offer better resistance to the elements. But, soft cases are generally cheaper, and if you get one with webbing on the outside it can be more modular than a hard case.

If you get a soft case, make sure the firearm is in a separate, padded compartment and nothing is rattling around in there that could catch your trigger.

Now, you don't have to buy a purpose built range bag or hard case for your gun, but you should be aware of how your firearm exists in space when it's in whatever bag you chose. For example, if you just throw it in a backpack, it could shift and you could be inadvertently pointing a loaded weapon at anyone standing next to you. Should something like a pencil get into that trigger guard and push against your trigger, you could have a very bad accident on your hands.

Lets do some hands on stuff, I'm tired of hearing myself talk. I'll give a quick explainer, then y'all can try it

Most ranges require that you firearm is cased or in a holster before you bring it inside. Some ask that your firearm is unloaded. Always be aware of the rules at the range you're going to before you go. Generally they're posted on the range's website.

When you arrive at a range, the check in procedure varies by location. Most require that you rent a lane, and pay money for the time on that lane. Some outdoor ranges will be loud, even from the parking lot, so it may be a good idea to put some hearing protection on until you get to your check-in location.

After you've checked in, you can go to the firing line. Some ranges will require that you wait until a ceasefire to go up to the firing line, some won't. In either case, keep your firearms in their case until you get into your lane. Then, in case your firearm making sure that the barrel stays in a safe direction.

A couple of ranges will have rules about how firearms are handed off while on the firing line. This can happen pretty frequently when you're with the chapter, we like to let everyone shoot our guns, so let me walk you through a couple of ways handoffs can happen.

The first, and probably easiest way, is to unload it, set it on a bench in your lane pointing downrange, and stepping back so your comrade can handle it. This works best when there aren't rules about multiple shooters sharing lanes, and if you have rifle or handgun specific lanes. Make sure your chamber is open (if you can), your magazine is out of the firearm, and the barrel is pointed down range.

Some ranges will require that your firearm be unloaded, cased, then taken off the firing line before it can go to another lane. You'll follow the same general process I just talked about, but instead of leaving your weapon on the bench you'll case it, take it away from the firing line, and wait for the range safety officer (RSO for short) to tell you to bring it to the next lane. Even if your firearm is cased, you should try to avoid people walking in front of your barrel, and makes sure it's pointed in a safe direction.

        Well, what if you're not at a range? What if you want to hand a firearm off to a comrade to look at? How do we do this safely? It's pretty easy. For a handgun, keep the barrel pointed in a safe direction. Grab  your barrel pointed in a safe dir


    Slide 6
        Loading your firearm (Don't really know what to say here either)
        Magazines, clips, single loading
    Slide 7
        WTF is this slide even saying? Guessing this is something to do with trigger?)
        Lets get into the nitty-gritty of shooting. There are a couple of things that can drastically change where your shot lands on paper, and any pro will tell you that if you screw something up, you should go back and re-examine these fundamentals to see if something went wrong. If you're shooting in a self defense scenario, you won't have the time to run through these fundamentals (like, alright are my feet set and hips pointed towards my target. Wait, hang on, stop trying to kill me for a second so I can get my trigger finger right!) They need to be automatic so you can place shots on target even in high stress scenarios.

        We'll start with the hardest one, trigger control. Regardless of what type of firearm you're shooting, proper placement of your trigger finger will squeeze the trigger straight back and wont cause the muzzle to deflect. This is much more important with handguns, because you dont have a stock or brace to keep the muzzle on target.

        Your trigger finger should be placed so that the trigger is in the center of the pad of your shooting hand (we'll figure out eye dominance/shooting hand later). It should be placed in the center of the trigger. If you're shooting a handgun that has a long trigger pull, like a revolver, a double action or a DA/SA, you can move closer to the joint to get a bit more strength.

        It's also important to squeeze the trigger, not jerk it. An uncontrolled pull of the trigger could move the muzzle off target and cause you to miss a shot. When you squeeze the trigger, make sure your finger and trigger come straight back. That is, make sure your trigger finger is isolated-none of your other fingers should move (or you risk pushing or pulling the gun) and the finger should move as parallel as possible to the muzzle.

        Trigger control is quite possibly the hardest part of shooting to master. It will probably be one of the fundamentals you screw up most often, and when it comes to hand guns can have the biggest impact on your shot placement. You will (and should!) spend quite a bit of time making sure your trigger pull is correct at the range. Does anyone have any questions before we move on?
        good image for this slide:
        https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsavannaharsenal.files.wordpress.com%2F2014%2F04%2Ftrigger-finger-placement.jpg&f=1&nofb=1
        Proper grip for both handguns and long guns
    Slide 8
        The way you grip and, in the case of rifles, shoulder your firearm, and the way you're standing, are two other key fundamentals of marksmanship. Fortunately, they're not as hard as trigger control and should become automatic fairly quickly.
        Sight picture, breathing control, trigger control
    Slide 9
        Grouping on paper (I disagree, I think this slide is about sight picture and sight alignment)
    Slide 10
        Questions? (Disagree, this is about different styles of safety devices)
