= Basic Firearms Safety and Operation

=== Course Objectives

Upon completion of this course, students should be able to:

* List the six rules of firearms safety, and articulate the reasoning behind each rule

* Understand how to make a firearm safe, safe carrying and handoff of firearms and be able to physically demonstrate safe handoff of firearms

* Demonstrate knowledge of range ettiequte, including proper safety procedures, when to approach the firing line, policing brass, hanging targets

* Be familiar with different classes of weapons and their basic operation, including bolt action rifles, semi-automatic rifles, shotguns, semi-automatic handguns, and revolvers

* Properly load and unload magazines for semi-automatic rifles and handguns, properly load and unload a revolver, a shotgun, and properly put a round in the chamber for bolt action rifles, semi-automatic weapons, shotguns and revolvers

* Explain proper trigger finger placement and movement and how it can affect shot placement

* Explain proper grip and stance, for both rifles and handguns

* Differentiate between sight picture and sight alignment, and explain how both impact the ability to hit the target

* Demonstrate ability to diagnose and correct weapons malfunctions

* Understand safe storage of firearms and its importance to community safety

=== Course Composition

The course will be composed of two portions: a classroom portion, including powerpoint and hands-on demonstrations, and a practical portion, that allows students to practice skills learned at the classroom portion

=== Course Assessments

There will be two course assessments.

The written portion will cover the most important sections of the course, and will be in multiple choice format. Everything on the written portion of the exam should be known, by heart, by every responsible firearm owner.

The practical portion will assess your ability to use a firearm safely, and effectively. You are not expected to be an expert marksman, or even a good shot, but you are expected to get the majority of the rounds on target.

For the practical portion, you will be graded on:

* Safe and effective use of eye and ear protection
* Safe casing and uncasing of your firearm
* Ability to listen to and interpret range commands
* Range etiquette
* Safe loading and unloading of firearms
* Pistol Marksmanship: 3 rounds, reload, 2 rounds, on target at 5 yd
* Rifle Marksmanship: 3 rounds, reload, 2 rounds, on target at 20 yd
* Safe and effective management of weapons malfunctions
