= Disaster Readiness

== Course Overview
This course is intended to teach basic skills and the preparations necessary for individuals and communities to thrive in common disaster scenarios. The course will cover common preparation techniques and supplies, forming readiness plans with families and comrades, and handling the stress involved. The primary goal of the course is to teach those who do not know what they do not know and provide a starting point for planning and preparation.

Students should come out of this course with enough knowledge to research and plan for the types of disasters they are likely to face, based on their own situations.

== Syllabus

1. General Rules of Readiness
2. Planning and Practice
3. Common Supplies
4. Specialized Supplies
5. Natural Disasters
6. Political Incidents
7. A Community Perspective
8. Starter Checklists

== Additional Resources
* https://www.fema.gov/preparedness-checklists-toolkits[FEMA Index]
* https://www.fema.gov/media-library/assets/documents/7877[FEMA Citizen's Guide]
* https://ready.gov
* https://www.aap.org/en-us/advocacy-and-policy/aap-health-initiatives/Children-and-Disasters/Pages/default.aspx[American Association of Pediatrics Guide]
* https://www.aspca.org/pet-care/general-pet-care/disaster-preparedness[ASPCA Pet Guide]