= Combat Liberalism: Notes

.Forms of Liberalism:
. To let things slide, or to lightly critique to "keep the peace" when someone is wrong
//.. list what should be done instead here
. To criticise in private instead of critiquing in front of the group
//.. list what to do instead
. To let things slide if they don't personally affect you
//.. list what to do instead
. Not obeying orders, thinking you know better than the party
// Fix the above line
//.. List what to do instead
. Personally attack or fight with comrades, intead of struggling against incorrect ideas for the betterment of the group
//.. list what to do instead
. To hear counter-revolutionary or incorrect views and not rebutt them 
//.. list what to do instead
. Failing to interact with the workers, whether by conducting propaganda or conducting investigations among them; Not behaving as a communist while among the masses
//.. what to do instead
. Allowing someone to harm the interest of the working class, without feeling angry, or trying to stop them
//..
. Half-assing things, or working without a plan or direction
//..
. Lacking humility, refusing to take "small tasks" because you're "too important"
//..
. To know what your flaws and mistakes are, but make no effort to correct them
//..

== Exercises

Check understanding ::
What is liberalism in this context?

Deconstruct each form of liberalism :: 
See what resonates with students. Where have these things come up in their lives. Which ones are they guilty of? How have these things affected their organizing in the past? 

Building structures resistant to liberalism ::

How do we protect against liberalism? How does the party guard against both left and right deviations? 

Correcting Liberalism in ourselves and our organizaitons ::
How do we go about rectifying liberal ideas in ourselves and our organizations? How do we work with liberal organizations? 

